spring:
  thymeleaf:
    prefix: classpath:/static/

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/finalproject?characterEncoding=utf8&useSSL=true
    username: root
    password: 961017

  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.MySQL5Dialect


  mail:
      host: smtp.163.com
      username: 13262771809@163.com
      password: xc123456
      default-encoding: utf-8


logging:
  level:
    org.springfromework.web: info


